# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_ChangeFixLeng.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(794, 515)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 20, 161, 41))
        self.label.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(430, 130, 161, 41))
        self.label_3.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_3.setObjectName("label_3")
        self.Btn__PreClampOffset = QtWidgets.QPushButton(Dialog)
        self.Btn__PreClampOffset.setGeometry(QtCore.QRect(610, 180, 141, 41))
        self.Btn__PreClampOffset.setObjectName("Btn__PreClampOffset")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(40, 290, 181, 41))
        self.label_7.setStyleSheet("font: 10pt \"微软雅黑\";")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(250, 290, 31, 41))
        self.label_8.setStyleSheet("font: 10pt \"微软雅黑\";")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(380, 290, 61, 41))
        self.label_9.setStyleSheet("font: 10pt \"微软雅黑\";")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(470, 290, 31, 41))
        self.label_10.setStyleSheet("font: 10pt \"微软雅黑\";")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(40, 360, 261, 41))
        self.label_11.setStyleSheet("font: 10pt \"微软雅黑\";")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(450, 360, 181, 41))
        self.label_12.setStyleSheet("font: 10pt \"微软雅黑\";")
        self.label_12.setObjectName("label_12")
        self.Btn_FixLengYes = QtWidgets.QPushButton(Dialog)
        self.Btn_FixLengYes.setGeometry(QtCore.QRect(90, 430, 141, 41))
        self.Btn_FixLengYes.setObjectName("Btn_FixLengYes")
        self.Btn_FixLengNo = QtWidgets.QPushButton(Dialog)
        self.Btn_FixLengNo.setGeometry(QtCore.QRect(520, 430, 141, 41))
        self.Btn_FixLengNo.setObjectName("Btn_FixLengNo")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(40, 126, 159, 45))
        self.label_4.setStyleSheet("font: 10pt \"微软雅黑\";")
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(40, 178, 159, 45))
        self.label_6.setStyleSheet("font: 10pt \"微软雅黑\";")
        self.label_6.setObjectName("label_6")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(40, 230, 159, 45))
        self.label_5.setStyleSheet("font: 10pt \"微软雅黑\";")
        self.label_5.setObjectName("label_5")
        self.Ceb_AllowEdit = QtWidgets.QCheckBox(Dialog)
        self.Ceb_AllowEdit.setGeometry(QtCore.QRect(40, 90, 91, 19))
        self.Ceb_AllowEdit.setCheckable(True)
        self.Ceb_AllowEdit.setChecked(False)
        self.Ceb_AllowEdit.setObjectName("Ceb_AllowEdit")
        self.Lne_FixWeiht = QtWidgets.QLineEdit(Dialog)
        self.Lne_FixWeiht.setGeometry(QtCore.QRect(230, 130, 151, 41))
        self.Lne_FixWeiht.setObjectName("Lne_FixWeiht")
        self.Lne_TheoryWeiht = QtWidgets.QLineEdit(Dialog)
        self.Lne_TheoryWeiht.setEnabled(False)
        self.Lne_TheoryWeiht.setGeometry(QtCore.QRect(230, 180, 151, 41))
        self.Lne_TheoryWeiht.setObjectName("Lne_TheoryWeiht")
        self.Lne_Density = QtWidgets.QLineEdit(Dialog)
        self.Lne_Density.setEnabled(False)
        self.Lne_Density.setGeometry(QtCore.QRect(230, 230, 151, 41))
        self.Lne_Density.setObjectName("Lne_Density")
        self.Lne_ErrRangeMinus = QtWidgets.QLineEdit(Dialog)
        self.Lne_ErrRangeMinus.setGeometry(QtCore.QRect(270, 290, 91, 41))
        self.Lne_ErrRangeMinus.setObjectName("Lne_ErrRangeMinus")
        self.Lne_LengthRangeMax = QtWidgets.QLineEdit(Dialog)
        self.Lne_LengthRangeMax.setGeometry(QtCore.QRect(310, 360, 101, 41))
        self.Lne_LengthRangeMax.setObjectName("Lne_LengthRangeMax")
        self.Lne_ErrRangePlus = QtWidgets.QLineEdit(Dialog)
        self.Lne_ErrRangePlus.setGeometry(QtCore.QRect(500, 290, 91, 41))
        self.Lne_ErrRangePlus.setObjectName("Lne_ErrRangePlus")
        self.Lne_WeightMax = QtWidgets.QLineEdit(Dialog)
        self.Lne_WeightMax.setGeometry(QtCore.QRect(650, 360, 111, 41))
        self.Lne_WeightMax.setObjectName("Lne_WeightMax")
        self.Lne_PreClampOffset = QtWidgets.QLineEdit(Dialog)
        self.Lne_PreClampOffset.setGeometry(QtCore.QRect(430, 180, 151, 41))
        self.Lne_PreClampOffset.setStyleSheet("background-color:black;\n"
"color:red;\n"
"font: 14pt \"微软雅黑\"")
        self.Lne_PreClampOffset.setObjectName("Lne_PreClampOffset")
        self.Lab_ReadLeng = QtWidgets.QLabel(Dialog)
        self.Lab_ReadLeng.setGeometry(QtCore.QRect(230, 20, 161, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Lab_ReadLeng.setFont(font)
        self.Lab_ReadLeng.setStyleSheet("font: 20pt \"微软雅黑\";")
        self.Lab_ReadLeng.setObjectName("Lab_ReadLeng")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(640, 480, 161, 21))
        self.label_2.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.label_2.setObjectName("label_2")
        self.Ceb_AllowEdit_2 = QtWidgets.QCheckBox(Dialog)
        self.Ceb_AllowEdit_2.setGeometry(QtCore.QRect(130, 90, 91, 19))
        self.Ceb_AllowEdit_2.setChecked(True)
        self.Ceb_AllowEdit_2.setObjectName("Ceb_AllowEdit_2")
        self.label_7.setBuddy(self.Lne_ErrRangeMinus)
        self.label_11.setBuddy(self.Lne_LengthRangeMax)
        self.label_4.setBuddy(self.Lne_FixWeiht)
        self.label_6.setBuddy(self.Lne_TheoryWeiht)
        self.label_5.setBuddy(self.Lne_Density)

        self.retranslateUi(Dialog)
        self.Ceb_AllowEdit_2.toggled['bool'].connect(self.Lne_TheoryWeiht.setVisible)
        self.Ceb_AllowEdit.toggled['bool'].connect(self.Lne_Density.setEnabled)
        self.Ceb_AllowEdit.toggled['bool'].connect(self.Lne_TheoryWeiht.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.Ceb_AllowEdit, self.Lne_FixWeiht)
        Dialog.setTabOrder(self.Lne_FixWeiht, self.Lne_TheoryWeiht)
        Dialog.setTabOrder(self.Lne_TheoryWeiht, self.Lne_Density)
        Dialog.setTabOrder(self.Lne_Density, self.Lne_PreClampOffset)
        Dialog.setTabOrder(self.Lne_PreClampOffset, self.Btn__PreClampOffset)
        Dialog.setTabOrder(self.Btn__PreClampOffset, self.Lne_ErrRangeMinus)
        Dialog.setTabOrder(self.Lne_ErrRangeMinus, self.Lne_ErrRangePlus)
        Dialog.setTabOrder(self.Lne_ErrRangePlus, self.Lne_LengthRangeMax)
        Dialog.setTabOrder(self.Lne_LengthRangeMax, self.Lne_WeightMax)
        Dialog.setTabOrder(self.Lne_WeightMax, self.Btn_FixLengYes)
        Dialog.setTabOrder(self.Btn_FixLengYes, self.Btn_FixLengNo)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "输入定尺(计量单位：毫米)"))
        self.label.setText(_translate("Dialog", "定尺长度（毫米):"))
        self.label_3.setText(_translate("Dialog", "预夹紧偏移："))
        self.Btn__PreClampOffset.setText(_translate("Dialog", "修改预夹偏移"))
        self.label_7.setText(_translate("Dialog", "合格误差范围（公斤）:(&4)"))
        self.label_8.setText(_translate("Dialog", "-"))
        self.label_9.setText(_translate("Dialog", "------"))
        self.label_10.setText(_translate("Dialog", "+"))
        self.label_11.setText(_translate("Dialog", "容许最大调节长度范围（毫米）:(&5)"))
        self.label_12.setText(_translate("Dialog", "对应重量（公斤）:(&7)"))
        self.Btn_FixLengYes.setText(_translate("Dialog", "修改"))
        self.Btn_FixLengNo.setText(_translate("Dialog", "取消"))
        self.label_4.setText(_translate("Dialog", "定重（公斤）:(&1)"))
        self.label_6.setText(_translate("Dialog", "理论重量（公斤）:(&2)"))
        self.label_5.setText(_translate("Dialog", "热态密度(吨/立方米):(&3)"))
        self.Ceb_AllowEdit.setText(_translate("Dialog", "允许编辑"))
        self.Lne_PreClampOffset.setText(_translate("Dialog", "500"))
        self.Lab_ReadLeng.setText(_translate("Dialog", "10000"))
        self.label_2.setText(_translate("Dialog", "快捷键 alt + 数字"))
        self.Ceb_AllowEdit_2.setText(_translate("Dialog", "显示/隐藏"))

