# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_ProductionDataQuery.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(741, 515)
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(180, 60, 87, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(40, 30, 72, 15))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(90, 60, 72, 15))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(90, 110, 72, 15))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(390, 70, 72, 15))
        self.label_4.setObjectName("label_4")
        self.comboBox_2 = QtWidgets.QComboBox(Dialog)
        self.comboBox_2.setGeometry(QtCore.QRect(180, 110, 87, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.cb_SteelType = QtWidgets.QComboBox(Dialog)
        self.cb_SteelType.setGeometry(QtCore.QRect(460, 70, 87, 22))
        self.cb_SteelType.setObjectName("cb_SteelType")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(280, 200, 101, 16))
        self.label_8.setObjectName("label_8")
        self.Lne_SetWeight = QtWidgets.QLineEdit(Dialog)
        self.Lne_SetWeight.setGeometry(QtCore.QRect(362, 200, 201, 21))
        self.Lne_SetWeight.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Lne_SetWeight.setObjectName("Lne_SetWeight")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(580, 200, 41, 16))
        self.label_9.setObjectName("label_9")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(280, 240, 101, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(500, 240, 31, 16))
        self.label_12.setObjectName("label_12")
        self.Lne_LengRangeFrom = QtWidgets.QLineEdit(Dialog)
        self.Lne_LengRangeFrom.setGeometry(QtCore.QRect(360, 240, 113, 21))
        self.Lne_LengRangeFrom.setObjectName("Lne_LengRangeFrom")
        self.Lne_LengRangeTo = QtWidgets.QLineEdit(Dialog)
        self.Lne_LengRangeTo.setGeometry(QtCore.QRect(540, 240, 113, 21))
        self.Lne_LengRangeTo.setObjectName("Lne_LengRangeTo")
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(120, 340, 101, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(Dialog)
        self.label_15.setGeometry(QtCore.QRect(120, 380, 101, 16))
        self.label_15.setObjectName("label_15")
        self.Ceb_SetWeightEn = QtWidgets.QCheckBox(Dialog)
        self.Ceb_SetWeightEn.setGeometry(QtCore.QRect(80, 200, 121, 19))
        self.Ceb_SetWeightEn.setObjectName("Ceb_SetWeightEn")
        self.Ceb_LengRangeEn = QtWidgets.QCheckBox(Dialog)
        self.Ceb_LengRangeEn.setGeometry(QtCore.QRect(80, 240, 121, 19))
        self.Ceb_LengRangeEn.setObjectName("Ceb_LengRangeEn")
        self.Ceb_TimeRangeEn = QtWidgets.QCheckBox(Dialog)
        self.Ceb_TimeRangeEn.setGeometry(QtCore.QRect(80, 280, 121, 19))
        self.Ceb_TimeRangeEn.setObjectName("Ceb_TimeRangeEn")
        self.Det_DateRangeFrom = QtWidgets.QDateEdit(Dialog)
        self.Det_DateRangeFrom.setGeometry(QtCore.QRect(300, 340, 110, 22))
        self.Det_DateRangeFrom.setObjectName("Det_DateRangeFrom")
        self.Det_DateRangeTo = QtWidgets.QDateEdit(Dialog)
        self.Det_DateRangeTo.setGeometry(QtCore.QRect(300, 380, 110, 22))
        self.Det_DateRangeTo.setObjectName("Det_DateRangeTo")
        self.Tet_TimeRangeFrom = QtWidgets.QTimeEdit(Dialog)
        self.Tet_TimeRangeFrom.setGeometry(QtCore.QRect(460, 340, 118, 22))
        self.Tet_TimeRangeFrom.setObjectName("Tet_TimeRangeFrom")
        self.Tet_TimeRangeTo = QtWidgets.QTimeEdit(Dialog)
        self.Tet_TimeRangeTo.setGeometry(QtCore.QRect(460, 380, 118, 22))
        self.Tet_TimeRangeTo.setObjectName("Tet_TimeRangeTo")
        self.Btn_Query = QtWidgets.QPushButton(Dialog)
        self.Btn_Query.setGeometry(QtCore.QRect(50, 440, 93, 28))
        self.Btn_Query.setObjectName("Btn_Query")
        self.Btn_Exit = QtWidgets.QPushButton(Dialog)
        self.Btn_Exit.setGeometry(QtCore.QRect(540, 440, 93, 28))
        self.Btn_Exit.setObjectName("Btn_Exit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "生产数据查询"))
        self.comboBox.setItemText(0, _translate("Dialog", "全部"))
        self.comboBox.setItemText(1, _translate("Dialog", "甲班"))
        self.comboBox.setItemText(2, _translate("Dialog", "乙班"))
        self.comboBox.setItemText(3, _translate("Dialog", "丙班"))
        self.comboBox.setItemText(4, _translate("Dialog", "丁班"))
        self.label.setText(_translate("Dialog", "数据查询"))
        self.label_2.setText(_translate("Dialog", "班次"))
        self.label_3.setText(_translate("Dialog", "流"))
        self.label_4.setText(_translate("Dialog", "钢种"))
        self.comboBox_2.setItemText(0, _translate("Dialog", "全部"))
        self.comboBox_2.setItemText(1, _translate("Dialog", "1流"))
        self.comboBox_2.setItemText(2, _translate("Dialog", "2流"))
        self.comboBox_2.setItemText(3, _translate("Dialog", "3流"))
        self.comboBox_2.setItemText(4, _translate("Dialog", "4流"))
        self.label_8.setText(_translate("Dialog", "设定重量"))
        self.Lne_SetWeight.setText(_translate("Dialog", "0"))
        self.label_9.setText(_translate("Dialog", "公斤"))
        self.label_11.setText(_translate("Dialog", "定尺范围"))
        self.label_12.setText(_translate("Dialog", "到"))
        self.Lne_LengRangeFrom.setText(_translate("Dialog", "0"))
        self.Lne_LengRangeTo.setText(_translate("Dialog", "0"))
        self.label_14.setText(_translate("Dialog", "起始时间"))
        self.label_15.setText(_translate("Dialog", "结束时间"))
        self.Ceb_SetWeightEn.setText(_translate("Dialog", "使用设定重量"))
        self.Ceb_LengRangeEn.setText(_translate("Dialog", "使用定尺范围"))
        self.Ceb_TimeRangeEn.setText(_translate("Dialog", "使用时间范围"))
        self.Btn_Query.setText(_translate("Dialog", "确定"))
        self.Btn_Exit.setText(_translate("Dialog", "退出"))

