# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_SetCamera.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(877, 607)
        self.horizontalSlider_Light = QtWidgets.QSlider(Dialog)
        self.horizontalSlider_Light.setGeometry(QtCore.QRect(230, 40, 511, 22))
        self.horizontalSlider_Light.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_Light.setObjectName("horizontalSlider_Light")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(760, 40, 81, 16))
        self.label_2.setStyleSheet("background-color :red")
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(740, 130, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.Btn_Exit = QtWidgets.QPushButton(Dialog)
        self.Btn_Exit.setGeometry(QtCore.QRect(740, 260, 93, 28))
        self.Btn_Exit.setObjectName("Btn_Exit")
        self.Btn_SaveData = QtWidgets.QPushButton(Dialog)
        self.Btn_SaveData.setGeometry(QtCore.QRect(740, 190, 93, 28))
        self.Btn_SaveData.setObjectName("Btn_SaveData")
        self.Lab_LightValue = QtWidgets.QLabel(Dialog)
        self.Lab_LightValue.setGeometry(QtCore.QRect(810, 40, 31, 16))
        self.Lab_LightValue.setStyleSheet("background-color :red")
        self.Lab_LightValue.setObjectName("Lab_LightValue")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(70, 530, 619, 35))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_41 = QtWidgets.QLabel(self.layoutWidget)
        self.label_41.setStyleSheet("\n"
"font: 75 12pt \"微软雅黑\";\n"
"\n"
"")
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.horizontalLayout.addWidget(self.label_41)
        self.Lne_SetCameraFlip = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Lne_SetCameraFlip.sizePolicy().hasHeightForWidth())
        self.Lne_SetCameraFlip.setSizePolicy(sizePolicy)
        self.Lne_SetCameraFlip.setMaximumSize(QtCore.QSize(120, 16777215))
        self.Lne_SetCameraFlip.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Lne_SetCameraFlip.setStyleSheet("\n"
"font: 75 12pt \"微软雅黑\";\n"
"\n"
"")
        self.Lne_SetCameraFlip.setObjectName("Lne_SetCameraFlip")
        self.horizontalLayout.addWidget(self.Lne_SetCameraFlip)
        self.layoutWidget1 = QtWidgets.QWidget(Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(120, 140, 505, 71))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_37 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_37.setStyleSheet("\n"
"font: 75 12pt \"微软雅黑\";\n"
"\n"
"")
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setObjectName("label_37")
        self.verticalLayout.addWidget(self.label_37)
        self.Lne_Threshold_f1 = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Lne_Threshold_f1.sizePolicy().hasHeightForWidth())
        self.Lne_Threshold_f1.setSizePolicy(sizePolicy)
        self.Lne_Threshold_f1.setMaximumSize(QtCore.QSize(120, 16777215))
        self.Lne_Threshold_f1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Lne_Threshold_f1.setStyleSheet("\n"
"font: 75 12pt \"微软雅黑\";\n"
"\n"
"")
        self.Lne_Threshold_f1.setObjectName("Lne_Threshold_f1")
        self.verticalLayout.addWidget(self.Lne_Threshold_f1)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 2, 1)
        self.label_38 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_38.setStyleSheet("\n"
"font: 75 12pt \"微软雅黑\";\n"
"\n"
"")
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.gridLayout.addWidget(self.label_38, 0, 1, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_39.setStyleSheet("\n"
"font: 75 12pt \"微软雅黑\";\n"
"\n"
"")
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.gridLayout.addWidget(self.label_39, 0, 2, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_40.setStyleSheet("\n"
"font: 75 12pt \"微软雅黑\";\n"
"\n"
"")
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName("label_40")
        self.gridLayout.addWidget(self.label_40, 0, 3, 1, 1)
        self.Lne_Threshold_f2 = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Lne_Threshold_f2.sizePolicy().hasHeightForWidth())
        self.Lne_Threshold_f2.setSizePolicy(sizePolicy)
        self.Lne_Threshold_f2.setMaximumSize(QtCore.QSize(120, 16777215))
        self.Lne_Threshold_f2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Lne_Threshold_f2.setStyleSheet("\n"
"font: 75 12pt \"微软雅黑\";\n"
"\n"
"")
        self.Lne_Threshold_f2.setObjectName("Lne_Threshold_f2")
        self.gridLayout.addWidget(self.Lne_Threshold_f2, 1, 1, 1, 1)
        self.Lne_Threshold_f3 = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Lne_Threshold_f3.sizePolicy().hasHeightForWidth())
        self.Lne_Threshold_f3.setSizePolicy(sizePolicy)
        self.Lne_Threshold_f3.setMaximumSize(QtCore.QSize(120, 16777215))
        self.Lne_Threshold_f3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Lne_Threshold_f3.setStyleSheet("\n"
"font: 75 12pt \"微软雅黑\";\n"
"\n"
"")
        self.Lne_Threshold_f3.setObjectName("Lne_Threshold_f3")
        self.gridLayout.addWidget(self.Lne_Threshold_f3, 1, 2, 1, 1)
        self.Lne_Threshold_f4 = QtWidgets.QLineEdit(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Lne_Threshold_f4.sizePolicy().hasHeightForWidth())
        self.Lne_Threshold_f4.setSizePolicy(sizePolicy)
        self.Lne_Threshold_f4.setMaximumSize(QtCore.QSize(120, 16777215))
        self.Lne_Threshold_f4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Lne_Threshold_f4.setStyleSheet("\n"
"font: 75 12pt \"微软雅黑\";\n"
"\n"
"")
        self.Lne_Threshold_f4.setObjectName("Lne_Threshold_f4")
        self.gridLayout.addWidget(self.Lne_Threshold_f4, 1, 3, 1, 1)
        self.Btn_CameraSetAeState_auto = QtWidgets.QPushButton(Dialog)
        self.Btn_CameraSetAeState_auto.setGeometry(QtCore.QRect(20, 40, 93, 28))
        self.Btn_CameraSetAeState_auto.setObjectName("Btn_CameraSetAeState_auto")
        self.Btn_CameraSetAeState_man = QtWidgets.QPushButton(Dialog)
        self.Btn_CameraSetAeState_man.setGeometry(QtCore.QRect(120, 40, 93, 28))
        self.Btn_CameraSetAeState_man.setObjectName("Btn_CameraSetAeState_man")
        self.Lab_CameraSetAeState = QtWidgets.QLabel(Dialog)
        self.Lab_CameraSetAeState.setGeometry(QtCore.QRect(80, 20, 72, 15))
        self.Lab_CameraSetAeState.setObjectName("Lab_CameraSetAeState")
        self.layoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_2.setGeometry(QtCore.QRect(120, 380, 505, 71))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_42 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_42.setStyleSheet("\n"
"font: 75 12pt \"微软雅黑\";\n"
"\n"
"")
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setObjectName("label_42")
        self.verticalLayout_2.addWidget(self.label_42)
        self.Lne_Threshold_ratio_f1 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.Lne_Threshold_ratio_f1.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Lne_Threshold_ratio_f1.sizePolicy().hasHeightForWidth())
        self.Lne_Threshold_ratio_f1.setSizePolicy(sizePolicy)
        self.Lne_Threshold_ratio_f1.setMaximumSize(QtCore.QSize(120, 16777215))
        self.Lne_Threshold_ratio_f1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Lne_Threshold_ratio_f1.setStyleSheet("\n"
"font: 75 12pt \"微软雅黑\";\n"
"\n"
"")
        self.Lne_Threshold_ratio_f1.setObjectName("Lne_Threshold_ratio_f1")
        self.verticalLayout_2.addWidget(self.Lne_Threshold_ratio_f1)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 2, 1)
        self.label_43 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_43.setStyleSheet("\n"
"font: 75 12pt \"微软雅黑\";\n"
"\n"
"")
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName("label_43")
        self.gridLayout_2.addWidget(self.label_43, 0, 1, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_44.setStyleSheet("\n"
"font: 75 12pt \"微软雅黑\";\n"
"\n"
"")
        self.label_44.setAlignment(QtCore.Qt.AlignCenter)
        self.label_44.setObjectName("label_44")
        self.gridLayout_2.addWidget(self.label_44, 0, 2, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_45.setStyleSheet("\n"
"font: 75 12pt \"微软雅黑\";\n"
"\n"
"")
        self.label_45.setAlignment(QtCore.Qt.AlignCenter)
        self.label_45.setObjectName("label_45")
        self.gridLayout_2.addWidget(self.label_45, 0, 3, 1, 1)
        self.Lne_Threshold_ratio_f2 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.Lne_Threshold_ratio_f2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Lne_Threshold_ratio_f2.sizePolicy().hasHeightForWidth())
        self.Lne_Threshold_ratio_f2.setSizePolicy(sizePolicy)
        self.Lne_Threshold_ratio_f2.setMaximumSize(QtCore.QSize(120, 16777215))
        self.Lne_Threshold_ratio_f2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Lne_Threshold_ratio_f2.setStyleSheet("\n"
"font: 75 12pt \"微软雅黑\";\n"
"\n"
"")
        self.Lne_Threshold_ratio_f2.setObjectName("Lne_Threshold_ratio_f2")
        self.gridLayout_2.addWidget(self.Lne_Threshold_ratio_f2, 1, 1, 1, 1)
        self.Lne_Threshold_ratio_f3 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.Lne_Threshold_ratio_f3.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Lne_Threshold_ratio_f3.sizePolicy().hasHeightForWidth())
        self.Lne_Threshold_ratio_f3.setSizePolicy(sizePolicy)
        self.Lne_Threshold_ratio_f3.setMaximumSize(QtCore.QSize(120, 16777215))
        self.Lne_Threshold_ratio_f3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Lne_Threshold_ratio_f3.setStyleSheet("\n"
"font: 75 12pt \"微软雅黑\";\n"
"\n"
"")
        self.Lne_Threshold_ratio_f3.setObjectName("Lne_Threshold_ratio_f3")
        self.gridLayout_2.addWidget(self.Lne_Threshold_ratio_f3, 1, 2, 1, 1)
        self.Lne_Threshold_ratio_f4 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.Lne_Threshold_ratio_f4.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Lne_Threshold_ratio_f4.sizePolicy().hasHeightForWidth())
        self.Lne_Threshold_ratio_f4.setSizePolicy(sizePolicy)
        self.Lne_Threshold_ratio_f4.setMaximumSize(QtCore.QSize(120, 16777215))
        self.Lne_Threshold_ratio_f4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Lne_Threshold_ratio_f4.setStyleSheet("\n"
"font: 75 12pt \"微软雅黑\";\n"
"\n"
"")
        self.Lne_Threshold_ratio_f4.setObjectName("Lne_Threshold_ratio_f4")
        self.gridLayout_2.addWidget(self.Lne_Threshold_ratio_f4, 1, 3, 1, 1)
        self.label_46 = QtWidgets.QLabel(Dialog)
        self.label_46.setGeometry(QtCore.QRect(150, 450, 490, 33))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_46.setFont(font)
        self.label_46.setStyleSheet("\n"
"font: 75 8pt \"微软雅黑\";\n"
"\n"
"")
        self.label_46.setAlignment(QtCore.Qt.AlignCenter)
        self.label_46.setObjectName("label_46")
        self.Ceb_Threshold_auto_f1 = QtWidgets.QCheckBox(Dialog)
        self.Ceb_Threshold_auto_f1.setGeometry(QtCore.QRect(140, 350, 91, 19))
        self.Ceb_Threshold_auto_f1.setObjectName("Ceb_Threshold_auto_f1")
        self.Ceb_Threshold_auto_f2 = QtWidgets.QCheckBox(Dialog)
        self.Ceb_Threshold_auto_f2.setGeometry(QtCore.QRect(270, 350, 91, 19))
        self.Ceb_Threshold_auto_f2.setObjectName("Ceb_Threshold_auto_f2")
        self.Ceb_Threshold_auto_f3 = QtWidgets.QCheckBox(Dialog)
        self.Ceb_Threshold_auto_f3.setGeometry(QtCore.QRect(400, 350, 91, 19))
        self.Ceb_Threshold_auto_f3.setObjectName("Ceb_Threshold_auto_f3")
        self.Ceb_Threshold_auto_f4 = QtWidgets.QCheckBox(Dialog)
        self.Ceb_Threshold_auto_f4.setGeometry(QtCore.QRect(520, 350, 91, 19))
        self.Ceb_Threshold_auto_f4.setObjectName("Ceb_Threshold_auto_f4")
        self.Ceb_Correct_auto_f1 = QtWidgets.QCheckBox(Dialog)
        self.Ceb_Correct_auto_f1.setGeometry(QtCore.QRect(140, 230, 91, 19))
        self.Ceb_Correct_auto_f1.setObjectName("Ceb_Correct_auto_f1")
        self.Ceb_Correct_auto_f3 = QtWidgets.QCheckBox(Dialog)
        self.Ceb_Correct_auto_f3.setGeometry(QtCore.QRect(400, 230, 91, 19))
        self.Ceb_Correct_auto_f3.setObjectName("Ceb_Correct_auto_f3")
        self.Ceb_Correct_auto_f2 = QtWidgets.QCheckBox(Dialog)
        self.Ceb_Correct_auto_f2.setGeometry(QtCore.QRect(270, 230, 91, 19))
        self.Ceb_Correct_auto_f2.setObjectName("Ceb_Correct_auto_f2")
        self.Ceb_Correct_auto_f4 = QtWidgets.QCheckBox(Dialog)
        self.Ceb_Correct_auto_f4.setGeometry(QtCore.QRect(520, 230, 91, 19))
        self.Ceb_Correct_auto_f4.setObjectName("Ceb_Correct_auto_f4")
        self.Lab_Camre_X = QtWidgets.QLabel(Dialog)
        self.Lab_Camre_X.setGeometry(QtCore.QRect(100, 310, 551, 181))
        self.Lab_Camre_X.setStyleSheet("background-color:cornflowerblue;\n"
"font: 75 12pt \"微软雅黑\";\n"
"color:yellow\n"
"")
        self.Lab_Camre_X.setText("")
        self.Lab_Camre_X.setAlignment(QtCore.Qt.AlignCenter)
        self.Lab_Camre_X.setObjectName("Lab_Camre_X")
        self.label_47 = QtWidgets.QLabel(Dialog)
        self.label_47.setGeometry(QtCore.QRect(300, 320, 151, 29))
        self.label_47.setStyleSheet("\n"
"font: 75 12pt \"微软雅黑\";\n"
"\n"
"")
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName("label_47")
        self.Lab_Camre_X_2 = QtWidgets.QLabel(Dialog)
        self.Lab_Camre_X_2.setGeometry(QtCore.QRect(110, 220, 541, 41))
        self.Lab_Camre_X_2.setStyleSheet("background-color:cornflowerblue;\n"
"font: 75 12pt \"微软雅黑\";\n"
"color:yellow\n"
"")
        self.Lab_Camre_X_2.setText("")
        self.Lab_Camre_X_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Lab_Camre_X_2.setObjectName("Lab_Camre_X_2")
        self.Lab_Camre_X_2.raise_()
        self.Lab_Camre_X.raise_()
        self.horizontalSlider_Light.raise_()
        self.label_2.raise_()
        self.pushButton_2.raise_()
        self.Btn_Exit.raise_()
        self.Btn_SaveData.raise_()
        self.Lab_LightValue.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.Btn_CameraSetAeState_auto.raise_()
        self.Btn_CameraSetAeState_man.raise_()
        self.Lab_CameraSetAeState.raise_()
        self.layoutWidget_2.raise_()
        self.label_46.raise_()
        self.Ceb_Threshold_auto_f1.raise_()
        self.Ceb_Threshold_auto_f2.raise_()
        self.Ceb_Threshold_auto_f3.raise_()
        self.Ceb_Threshold_auto_f4.raise_()
        self.Ceb_Correct_auto_f1.raise_()
        self.Ceb_Correct_auto_f3.raise_()
        self.Ceb_Correct_auto_f2.raise_()
        self.Ceb_Correct_auto_f4.raise_()
        self.label_47.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "视频参数调整"))
        self.label_2.setText(_translate("Dialog", "亮度："))
        self.pushButton_2.setText(_translate("Dialog", "使用默认值"))
        self.Btn_Exit.setText(_translate("Dialog", "退出"))
        self.Btn_SaveData.setText(_translate("Dialog", "保存"))
        self.Lab_LightValue.setText(_translate("Dialog", "0"))
        self.label_41.setText(_translate("Dialog", " 0:水平翻转  1:垂直翻转  -1:全翻转  2:不翻转"))
        self.Lne_SetCameraFlip.setText(_translate("Dialog", "0"))
        self.label_37.setText(_translate("Dialog", "1流亮阈值:"))
        self.Lne_Threshold_f1.setText(_translate("Dialog", "0"))
        self.label_38.setText(_translate("Dialog", "2流亮阈值:"))
        self.label_39.setText(_translate("Dialog", "3流亮阈值:"))
        self.label_40.setText(_translate("Dialog", "4流亮阈值:"))
        self.Lne_Threshold_f2.setText(_translate("Dialog", "0"))
        self.Lne_Threshold_f3.setText(_translate("Dialog", "0"))
        self.Lne_Threshold_f4.setText(_translate("Dialog", "0"))
        self.Btn_CameraSetAeState_auto.setText(_translate("Dialog", "自动调整"))
        self.Btn_CameraSetAeState_man.setText(_translate("Dialog", "手动调整"))
        self.Lab_CameraSetAeState.setText(_translate("Dialog", "调整模式"))
        self.label_42.setText(_translate("Dialog", "1流阈值比:"))
        self.Lne_Threshold_ratio_f1.setText(_translate("Dialog", "0.4"))
        self.label_43.setText(_translate("Dialog", "2流阈值比:"))
        self.label_44.setText(_translate("Dialog", "3流阈值比:"))
        self.label_45.setText(_translate("Dialog", "4流阈值比:"))
        self.Lne_Threshold_ratio_f2.setText(_translate("Dialog", "0.4"))
        self.Lne_Threshold_ratio_f3.setText(_translate("Dialog", "0.4"))
        self.Lne_Threshold_ratio_f4.setText(_translate("Dialog", "0.4"))
        self.label_46.setText(_translate("Dialog", "公式:判断阈值 = 设定阈值 * 拉速 * 阈值比(默认0.4)"))
        self.Ceb_Threshold_auto_f1.setText(_translate("Dialog", "自动调整"))
        self.Ceb_Threshold_auto_f2.setText(_translate("Dialog", "自动调整"))
        self.Ceb_Threshold_auto_f3.setText(_translate("Dialog", "自动调整"))
        self.Ceb_Threshold_auto_f4.setText(_translate("Dialog", "自动调整"))
        self.Ceb_Correct_auto_f1.setText(_translate("Dialog", "自动调重"))
        self.Ceb_Correct_auto_f3.setText(_translate("Dialog", "自动调重"))
        self.Ceb_Correct_auto_f2.setText(_translate("Dialog", "自动调重"))
        self.Ceb_Correct_auto_f4.setText(_translate("Dialog", "自动调重"))
        self.label_47.setText(_translate("Dialog", "自动调整阈值比:"))
