# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_SetFurNo.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(430, 310)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setStyleSheet("font: 12pt \\\"微软雅黑\\\";")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.Lne_SetFurNo = QtWidgets.QLineEdit(Dialog)
        self.Lne_SetFurNo.setObjectName("Lne_SetFurNo")
        self.horizontalLayout.addWidget(self.Lne_SetFurNo)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setStyleSheet("font: 12pt \\\"微软雅黑\\\";")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.Lne_SetFurNum = QtWidgets.QLineEdit(Dialog)
        self.Lne_SetFurNum.setObjectName("Lne_SetFurNum")
        self.horizontalLayout.addWidget(self.Lne_SetFurNum)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 2)
        self.LW_SetFurNo = QtWidgets.QListWidget(Dialog)
        self.LW_SetFurNo.setObjectName("LW_SetFurNo")
        self.gridLayout.addWidget(self.LW_SetFurNo, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.Btn_addFurNum = QtWidgets.QPushButton(Dialog)
        self.Btn_addFurNum.setObjectName("Btn_addFurNum")
        self.verticalLayout.addWidget(self.Btn_addFurNum)
        self.Btn_delFurNum = QtWidgets.QPushButton(Dialog)
        self.Btn_delFurNum.setObjectName("Btn_delFurNum")
        self.verticalLayout.addWidget(self.Btn_delFurNum)
        self.Btn_Exit = QtWidgets.QPushButton(Dialog)
        self.Btn_Exit.setObjectName("Btn_Exit")
        self.verticalLayout.addWidget(self.Btn_Exit)
        self.gridLayout.addLayout(self.verticalLayout, 1, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "设定炉号"))
        self.label.setText(_translate("Dialog", "当前炉号"))
        self.label_2.setText(_translate("Dialog", "根数"))
        self.Btn_addFurNum.setText(_translate("Dialog", "添加"))
        self.Btn_delFurNum.setText(_translate("Dialog", "删除"))
        self.Btn_Exit.setText(_translate("Dialog", "退出"))
