# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_SetFurNo.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(394, 247)
        self.Btn_SetFurNoYes = QtWidgets.QPushButton(Dialog)
        self.Btn_SetFurNoYes.setGeometry(QtCore.QRect(60, 140, 101, 41))
        self.Btn_SetFurNoYes.setObjectName("Btn_SetFurNoYes")
        self.Btn_SetFurNoNo = QtWidgets.QPushButton(Dialog)
        self.Btn_SetFurNoNo.setGeometry(QtCore.QRect(210, 140, 101, 41))
        self.Btn_SetFurNoNo.setObjectName("Btn_SetFurNoNo")
        self.LabInput_SetFurNo = QtWidgets.QTextEdit(Dialog)
        self.LabInput_SetFurNo.setGeometry(QtCore.QRect(160, 70, 171, 41))
        self.LabInput_SetFurNo.setStyleSheet("font: 12pt \\\"微软雅黑\\\";")
        self.LabInput_SetFurNo.setObjectName("LabInput_SetFurNo")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(40, 70, 111, 41))
        self.label.setStyleSheet("font: 12pt \\\"微软雅黑\\\";")
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Btn_SetFurNoYes.setText(_translate("Dialog", "确定"))
        self.Btn_SetFurNoNo.setText(_translate("Dialog", "取消"))
        self.label.setText(_translate("Dialog", "当前炉号:"))
