# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_SetTeam.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(536, 423)
        self.Cbb_SetTeam = QtWidgets.QComboBox(Dialog)
        self.Cbb_SetTeam.setGeometry(QtCore.QRect(150, 200, 261, 41))
        self.Cbb_SetTeam.setObjectName("Cbb_SetTeam")
        self.Cbb_SetTeam.addItem("")
        self.Cbb_SetTeam.addItem("")
        self.Cbb_SetTeam.addItem("")
        self.Cbb_SetTeam.addItem("")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 150, 141, 31))
        self.label.setObjectName("label")
        self.Btn_TeamYes = QtWidgets.QPushButton(Dialog)
        self.Btn_TeamYes.setGeometry(QtCore.QRect(60, 300, 101, 41))
        self.Btn_TeamYes.setObjectName("Btn_TeamYes")
        self.Btn_TeamNo = QtWidgets.QPushButton(Dialog)
        self.Btn_TeamNo.setGeometry(QtCore.QRect(380, 300, 101, 41))
        self.Btn_TeamNo.setObjectName("Btn_TeamNo")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(190, 70, 201, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "改变班次"))
        self.Cbb_SetTeam.setItemText(0, _translate("Dialog", "甲班"))
        self.Cbb_SetTeam.setItemText(1, _translate("Dialog", "乙班"))
        self.Cbb_SetTeam.setItemText(2, _translate("Dialog", "丙班"))
        self.Cbb_SetTeam.setItemText(3, _translate("Dialog", "丁班"))
        self.label.setText(_translate("Dialog", "选择新工作班组:"))
        self.Btn_TeamYes.setText(_translate("Dialog", "确定"))
        self.Btn_TeamNo.setText(_translate("Dialog", "取消"))
        self.label_2.setText(_translate("Dialog", "选择新工作班组:"))
