# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_SetLocNo.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(218, 147)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Labtxt_ClassNo = QtWidgets.QLabel(Dialog)
        self.Labtxt_ClassNo.setStyleSheet("font: 12pt \\\"微软雅黑\\\";")
        self.Labtxt_ClassNo.setObjectName("Labtxt_ClassNo")
        self.verticalLayout.addWidget(self.Labtxt_ClassNo)
        self.LabInput_LocNo = QtWidgets.QTextEdit(Dialog)
        self.LabInput_LocNo.setStyleSheet("font: 12pt \\\"微软雅黑\\\";")
        self.LabInput_LocNo.setObjectName("LabInput_LocNo")
        self.verticalLayout.addWidget(self.LabInput_LocNo)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.Btn_LocNoYes = QtWidgets.QPushButton(Dialog)
        self.Btn_LocNoYes.setObjectName("Btn_LocNoYes")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Btn_LocNoYes)
        self.Btn_LocNoNo = QtWidgets.QPushButton(Dialog)
        self.Btn_LocNoNo.setObjectName("Btn_LocNoNo")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.Btn_LocNoNo)
        self.gridLayout.addLayout(self.formLayout, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "修改连铸机号"))
        self.Labtxt_ClassNo.setText(_translate("Dialog", "当前连铸机号:"))
        self.Btn_LocNoYes.setText(_translate("Dialog", "确定"))
        self.Btn_LocNoNo.setText(_translate("Dialog", "取消"))
