# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_ProductionData.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1113, 713)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 30, 72, 15))
        self.label.setObjectName("label")
        self.Btn_Query = QtWidgets.QPushButton(Dialog)
        self.Btn_Query.setGeometry(QtCore.QRect(100, 90, 93, 28))
        self.Btn_Query.setObjectName("Btn_Query")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(380, 90, 111, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(560, 90, 111, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.Btn_Exit = QtWidgets.QPushButton(Dialog)
        self.Btn_Exit.setGeometry(QtCore.QRect(740, 90, 111, 31))
        self.Btn_Exit.setObjectName("Btn_Exit")
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(800, 620, 111, 31))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Dialog)
        self.pushButton_6.setGeometry(QtCore.QRect(970, 620, 111, 31))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(Dialog)
        self.pushButton_7.setGeometry(QtCore.QRect(230, 620, 111, 31))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(Dialog)
        self.pushButton_8.setGeometry(QtCore.QRect(60, 620, 111, 31))
        self.pushButton_8.setObjectName("pushButton_8")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(520, 620, 51, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(580, 620, 41, 16))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "生产数据管理对话框"))
        self.label.setText(_translate("Dialog", "数据库名："))
        self.Btn_Query.setText(_translate("Dialog", "查询"))
        self.pushButton_2.setText(_translate("Dialog", "导出Excel表"))
        self.pushButton_3.setText(_translate("Dialog", "打印"))
        self.Btn_Exit.setText(_translate("Dialog", "退出"))
        self.pushButton_5.setText(_translate("Dialog", "下页"))
        self.pushButton_6.setText(_translate("Dialog", "尾页"))
        self.pushButton_7.setText(_translate("Dialog", "上页"))
        self.pushButton_8.setText(_translate("Dialog", "首页"))
        self.label_2.setText(_translate("Dialog", "Page:"))
        self.label_3.setText(_translate("Dialog", "1/1"))
