# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_SetSteelData.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(891, 563)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(110, 30, 111, 21))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(670, 40, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(660, 80, 111, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.Btn_Exit = QtWidgets.QPushButton(Dialog)
        self.Btn_Exit.setGeometry(QtCore.QRect(710, 510, 111, 28))
        self.Btn_Exit.setObjectName("Btn_Exit")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(30, 130, 111, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(110, 190, 111, 21))
        self.label_2.setObjectName("label_2")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(670, 190, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(660, 230, 111, 28))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Dialog)
        self.pushButton_6.setGeometry(QtCore.QRect(30, 280, 111, 28))
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(110, 350, 111, 21))
        self.label_3.setObjectName("label_3")
        self.pushButton_7 = QtWidgets.QPushButton(Dialog)
        self.pushButton_7.setGeometry(QtCore.QRect(660, 400, 111, 28))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(Dialog)
        self.pushButton_8.setGeometry(QtCore.QRect(30, 440, 111, 28))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(Dialog)
        self.pushButton_9.setGeometry(QtCore.QRect(670, 360, 93, 28))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(Dialog)
        self.pushButton_10.setGeometry(QtCore.QRect(660, 440, 111, 28))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(Dialog)
        self.pushButton_11.setGeometry(QtCore.QRect(660, 270, 111, 28))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(Dialog)
        self.pushButton_12.setGeometry(QtCore.QRect(660, 120, 111, 28))
        self.pushButton_12.setObjectName("pushButton_12")
        self.cb_lengthType = QtWidgets.QComboBox(Dialog)
        self.cb_lengthType.setGeometry(QtCore.QRect(160, 70, 371, 41))
        self.cb_lengthType.setObjectName("cb_lengthType")
        self.cb_SectionTyoe = QtWidgets.QComboBox(Dialog)
        self.cb_SectionTyoe.setGeometry(QtCore.QRect(160, 230, 371, 41))
        self.cb_SectionTyoe.setObjectName("cb_SectionTyoe")
        self.cb_steelType = QtWidgets.QComboBox(Dialog)
        self.cb_steelType.setGeometry(QtCore.QRect(160, 380, 371, 41))
        self.cb_steelType.setObjectName("cb_steelType")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "定尺选择（所有流）"))
        self.label.setText(_translate("Dialog", "定尺列表"))
        self.pushButton.setText(_translate("Dialog", "添加新定尺"))
        self.pushButton_2.setText(_translate("Dialog", "删除所选定尺"))
        self.Btn_Exit.setText(_translate("Dialog", "取消"))
        self.pushButton_4.setText(_translate("Dialog", "切换定尺"))
        self.label_2.setText(_translate("Dialog", "断面列表"))
        self.pushButton_3.setText(_translate("Dialog", "添加新断面"))
        self.pushButton_5.setText(_translate("Dialog", "删除所选断面"))
        self.pushButton_6.setText(_translate("Dialog", "切换断面"))
        self.label_3.setText(_translate("Dialog", "钢种列表"))
        self.pushButton_7.setText(_translate("Dialog", "删除所选钢种"))
        self.pushButton_8.setText(_translate("Dialog", "切换钢种"))
        self.pushButton_9.setText(_translate("Dialog", "添加新钢种"))
        self.pushButton_10.setText(_translate("Dialog", "修改所选钢种"))
        self.pushButton_11.setText(_translate("Dialog", "修改所选断面"))
        self.pushButton_12.setText(_translate("Dialog", "修改所选定尺"))
